apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-nginx
          image: nginx
  replicas: 6
