apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-nginx
  labels:
    name: myapp
    type: prod

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: prod

    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 4
