apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica
  labels:
    name: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp-pod
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
